<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
 $vars = Mage::getSingleton("core/session")->getPsonifyVars();
 $loginLink = $vars['loginLink'];
?>
<style>
.settingsContainer {
	background-color: #f8fdff;
    border-color: #e2e2e2;
    border-radius: 20px;
    border-style: solid;
    border-width: 5px;
    margin: 30px auto;
    min-height: 400px;
    width: 70%;
	padding:5%;
	font-family:Lucida Console;
}
.highlightContainer{
	background-color: white;
    border-radius: 20px;
    border-style: solid;
    border-width: 1px;
    margin: 100px auto;
    padding: 3% 10%;
    position: relative;
    width: 82%;
}
</style>
<div class="settingsContainer"> 
	<h3> Psonify settings</h3>
	
	<div class="highlightContainer" >
		Select One of the desired templates for abandoned carts from <a href="<?php echo $loginLink?>" target="__blank" >here<a>
	</div>

</div>